name: Check pull requests into live branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Restrict branches against live
        run: |
          if [ "${{ github.head_ref }}" != "main" ] && [ "${{ github.base_ref }}" == "live" ]; then
            echo "Merge requests to live branch are only allowed from main branch."
            exit 1
          fi